#!/usr/bin/env python3
from workout.generator import Generator
from workout.templates import get_random_template
from workout.formatters import CliFormatter
import argparse
import random
from datetime import datetime


def main(args):
    if args.date is None:
        date = datetime.now()
    else:
        date = args.date
    random.seed(date.strftime('%Y-%m-%d'))

    g = Generator(args.volume, args.sets, formatter=CliFormatter())
    print(g.generate_by_template(get_random_template()))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Get workout of the day')
    parser.add_argument('--volume', default=300, type=int, help='Total number of reps in this workout')
    parser.add_argument('--sets', default=5, type=int, help='Total number of sets in this workout')
    parser.add_argument('--date', type=lambda s: datetime.strptime(s, '%Y-%m-%d'), help='date')
    main(parser.parse_args())
