#!/usr/bin/env python3
from workout.generator import Generator
from workout.templates import get_random_template, get_template, TEMPLATES
from workout.formatters import CliFormatter
import argparse
import random
from datetime import datetime


def main(args):
    if args.date is None:
        date = datetime.now()
    else:
        date = args.date
    random.seed(date.strftime('%Y-%m-%d'))

    g = Generator(args.volume, args.reps, formatter=CliFormatter())

    if args.type is not None:
        template = get_template(args.type)
    else:
        template = get_random_template()

    print(g.generate_by_template(template))


if __name__ == '__main__':

    type_choices = TEMPLATES.keys()

    parser = argparse.ArgumentParser(description='Get workout of the day')
    parser.add_argument('-v', '--volume', default=300, type=int, help='Total number of total reps in this workout. (Default: 300)')
    parser.add_argument('-r', '--reps', default=10, type=int, help='Total number of reps in this workout. (Default: 10)')
    parser.add_argument('-d', '--date', type=lambda s: datetime.strptime(s, '%Y-%m-%d'), help='date. (Default: today)')
    parser.add_argument('-t', '--type', type=str, choices=type_choices, help="type of excersise. (Default: random)")
    main(parser.parse_args())
